### ISSUE TITLE
[ue4] Spine Widget flickering on mobile

### ISSUE THREAD

**Issue by GloryOfNight** [EsotericSoftware/spine-runtimes#1458]
Hi! I got a problem with using Spine Widget. During PIE session everything seems fine, but when I build application for Android platform it's got some flickering effect. Sprites randomly disappear for ~1 frame and then rendered again. 

Here a video (sorry for such capture, but there was no other way): 
https://youtu.be/IGSilTqUyY8
![Z4gAzjDWnW8](https://user-images.githubusercontent.com/23162722/63344181-7c369100-c358-11e9-8394-56d2a8f4fc4c.jpg)

**Comment by badlogic** [comment]
Can you reproduce this with our spine-ue4 example on mobile? What UE4 version are you using? What spine-ue4 version are you using?

**Comment by GloryOfNight** [comment]
Im using 4.21 project version, also I cannot reproduce bug because sample project version > 4.21 and sample assets simply don't want load & generate build errors. 
More about bug reproduce I will say tomorrow, when I install 4.22 unreal engine ver. 

Spine-runtimes used from 3.8 branch, latest commit

**Comment by GloryOfNight** [comment]
Issue was reproduced on example project with editor version 4.22. The same flickering effect (maybe not so regular, but it has).

**Comment by badlogic** [comment]
I couldn't reproduce the flicker on my iPad. I fixed another issue related to this yesterday. Could you please grab the latest 3.8 branch code for spine-ue4 and give that a try?

**Comment by GloryOfNight** [comment]
I updated SpineRuntimes and issue still valid. The same flickering effect. 
Also, for the note. Ive testing this on Android devices.

**Comment by GloryOfNight** [comment]
I can make some sort of demo project for you, where i have issue reproduced.

**Comment by badlogic** [comment]
@GloryOfNight a demo project would be most excellent!

**Comment by GloryOfNight** [comment]
@badlogic 

Here it is: [link](https://drive.google.com/drive/folders/1aVRy9x5jseWxRrZfsuaEmO-KWjX6u3vi?usp=sharing)

Please note, that issue may appear after some time (~15 secs) after launch. If issue wasn't appear try relaunch application and wait some time again. 
I also uploaded to folder APK and Video file that demonstrates issue. Project in .zip was build on UE 4.21.

**Comment by GloryOfNight** [comment]
Hi! Is everything ok?

**Comment by badlogic** [comment]
@GloryOfNight I can reproduce it, but I have not found a solution.

**Comment by GloryOfNight** [comment]
Hi! Any news on that issue?

**Comment by jashking** [comment]
hello, any updates？we have the same issue

**Comment by badlogic** [comment]
@GloryOfNight @jashking I'm afraid we haven't made any progress on this. I'll reach out to Epic on their issue tracker, but I'd assume they'll close the issue due to the complexity of the reproduction project. I'll update this issue with a link to the Epic tracker once I've filed it.

**Comment by jashking** [comment]
Is it need to modify engine source? My project is built from source so I can modify engine source if you have any workaround

**Comment by badlogic** [comment]
@jashking I do not know. While I can reproduce the flicker, I have no idea why it occurs. We submit the correct vertex and material data to the engine every frame. I'm afraid I do not know enough about the UE4 internals to understand what goes wrong inside the engine.

**Comment by jashking** [comment]
Could you send me a demo project to report this issue, so I can send it to Epic directly because we are their licensee

**Comment by badlogic** [comment]
@GloryOfNight has posted a demo project above that reproduces the flicker https://github.com/EsotericSoftware/spine-runtimes/issues/1458#issuecomment-534544012

It would be great if you could use your connections to help resolve this issue. Us just posting this on Epic's issue tracker is unlikely to get attention, as the project includes our whole runtime.

**Comment by jashking** [comment]
We found the problem, and it was fixed after 4.23.1
![fix](https://user-images.githubusercontent.com/2841098/69342964-9493b000-0ca7-11ea-8ef1-f0073bae0a85.png)

**Comment by badlogic** [comment]
@jashking great find. I'll confirm with the repro project in 4.23.1+. Trying to think of a way to fix this for < 4.23.1 without having to change the engine sources directly. If you have any ideas, let me know.

**Comment by badlogic** [comment]
Thank you for your help @jashking. I have found a work around to make this work in UE < 4.23.1+. We now subclass `FSlateBrush` ourself instead of using `FSlateMaterialBrush`. As in the fix in the engine sources, we do not manually clean up the resources. This way the fix also works for projects with UE versions < 4.23.1. This brush is not exposed to the outside, so the change should be save from a serialization perspective as well.

I've pushed this to both the 3.8 and 3.9-beta branches. @GloryOfNight please give it a try and let me know if you still see the flicker in your production project.

**Comment by GloryOfNight** [comment]
That fixed issue for me. Thanks!

**Comment by badlogic** [comment]
Awesome!
