### ISSUE TITLE
spine-phaser runtime, SpineGameObject.setDisplaySize()?

### ISSUE THREAD

**Issue by saintflow47** [EsotericSoftware/spine-runtimes#2313]
Using the current Phaser Spine runtimes, I was able to scale my SpineGameObject via .setDisplaySize(). Had a quick chat with @photonstorm about it and we thought it might be best to bring it up here.

With the new official spine-phaser runtime the only way to scale a SpineGameObject seems to be setScale() and I struggle to find any size reference within the SpineGameObject that i can use to properly make use of setScale() to replicate my current way of scaling with setDisplaySize().

I tried using the boundsProvider.calculateBounds() function and animationStateData.skeletonData.width/height, neither lead to predictable results with my current assets.

I would love to know what the supposed way of working is to scale an object to a certain pixel size or if it might be possible to re-enable setDisplaySize(). Thanks a lot!

**Comment by badlogic** [comment]
I believe this is a bug I just fixed in the latest 4.1.36 release (and 4.2.17 beta release).

The following works as expected.

```
const spineboy = this.add.spine(400, 500, 'spineboy-data', "spineboy-atlas");            
spineboy.displayWidth = 200;
spineboy.displayHeight = spineboy.height / spineboy.width * 200;
```

`spineboy.width` and `spineboy.height` are calculated using a default `SetupPoseBoundsProvider`. It will generate an axis aligned bounding box that tightly encloses all visible attachments of the skeleton's setup pose and set its width and height on the `SpineGameObject`. All of this happens in the `add.spine()` method.

I then set the `displayWidth` to `200` and scale the `displayHeight` accordingly based on the ratio `height / width` times the display height `200`.

The `SetupPoseBoundsProvider` is usually good enough. You can also use the `SkinsAndAnimationBoundsProvider` for more complex scenarios where you want the bounding box to eclose all visible attachments of a combination of skins and for a specific animation. Or you can write your own bounds provider.

**Comment by saintflow47** [comment]
Thank you for your reply Mario!
Sadly, still not working like all of the previous spine runtimes for phaser.
I can use it like you proposed to (even though i do get typescript errors with these attributes), but the bounds seem to be calculated differently than before when i was able to use setDisplaySize on the SpineGameObject and thus the resulting image size is different as well.

Here are 3 examples of the end results on my end
 
previous spine runtime for phaser
https://drive.google.com/file/d/17QH1A5WXNwAhzKqPghwC6Jb-KUhxDbcg/view?usp=sharing

new runtime without setting any size or scale
https://drive.google.com/file/d/1QAwEQAm0-3f55Qxnuu95H1wp5yfwXQre/view?usp=sharing

new runtime with setting displayWidth/displayHeight
https://drive.google.com/file/d/19Sc1xQU2GvmSjyX3Rt4UjF30KXOaJdBa/view?usp=sharing

If you tell me the way the bounds are calculated right now is "the right way" and it will most likely not change, I will need to get my spine files adjusted. I understand i could also write a provider myself trying to mimic the previous behavior but to be honest I think that's a bit more than i can handle. Thanks for your time, much appreciated!

**Comment by badlogic** [comment]
Please send me a minimal executable example. It's impossible to help just
based on screenshots I'm afraid.

**Comment by saintflow47** [comment]
I completely understand where you are coming from Mario, but i dont even know what that example should show you (i think whats there right now is working like you intended, just not working like it used to do, at least in phaser)
Basically, I extend the SpineGameObject Class, create a new object of that class and then used setDisplaySize and now use .displayWidth/Height to scale it. previously, bubbles were scaled to the same size, now they are not.

I dont understand much of spine, but my guess is the artist just used invisible skeleton things for some of the animations and thats why they might look different. It just wasnt an issue before switching to the official runtime so i thought everything is alright with my spine files.

**Comment by badlogic** [comment]
Possibly. I'd still like to fix it. However, doing that just based on the
code differences between our SpineGameObject and Phaser's equivalent isn't
possible. If you can share the skeleton and a code snippet how you set the
disolay size, I can figure it out.

**Comment by saintflow47** [comment]
Got it, I hope this helps!
https://drive.google.com/file/d/1joHjuAncGhZQV5ynDYBpPif4so1DH1hu/view?usp=sharing

If you need anything else just give me a shout i will provide what i can to help!
