### ISSUE TITLE
[Phaser] rendering corruption

### ISSUE THREAD

**Issue by spayton** [EsotericSoftware/spine-runtimes#2348]
The batcher isn't finishing off in all cases where it should do, which causes rendering problems.

This was noticed when a scene is constructed with phaser images and spines when a spine's visible property was set false.

eg here spine1 & image1 will suffer varying corruption
```
scene1
├─── container1
│    ├─── spine1
│    └─── spine2 (.visible = false)
└─── image1
```

The problem is SpineGameObject.willRender(), this has been over simplified from the Phaser's own SpineGameObject to return false if this.visible is false.

Unfortunately, this function does more than it's name suggests, it is used by the calling framework to initiaite a tidy up when necessary based on a number of properties (renderflags, camera, last in list) and is not a simple visibility test.

**Comment by badlogic** [comment]
Ah, I think that would also explain why the camera pipeline test doesn't work as intended. I see what I can do.

**Comment by badlogic** [comment]
This should be fixed now. I'll release a new package to NPM later today.

**Comment by spayton** [comment]
Ok, I'll test it later

**Comment by spayton** [comment]
Still not working.  If !visible then it should still determine if a rebind is needed, rather than just returning.

**Comment by badlogic** [comment]
Huh but that's what the Phaser Spine runtime also did. I'll try again, sorry!

**Comment by spayton** [comment]
Here's my modified willRender() which worked for me, I just overrode the plugin version with this .js snippet

```js
var GameObjectRenderMask = 15;

var result = (!this.skeleton || !(GameObjectRenderMask !== this.renderFlags || (this.cameraFilter !== 0 && (this.cameraFilter & camera.id))));

if (/*!container && */!result && this.parentContainer) {
    // var plugin = this.plugin;
    var plugin = this.plugin;
    var sceneRenderer = plugin.webGLRenderer;

    // if (plugin.gl && sceneRenderer.batcher.isDrawing)
    if (this.scene.renderer.gl && sceneRenderer.batcher.isDrawing) {
        sceneRenderer.end();

        // plugin.scene.renderer.pipelines.rebind();	// maybe this is better
        this.scene.renderer.pipelines.rebind();
    }
}

return result;
```

This was besed on Phaser's plugin, the important bit is that its not a simple test on the .visible property.

I didn't PR this as being .ts I'd have to make some other properties available at the very least, and wasn't too familiar with the code and how you do things.

**Comment by badlogic** [comment]
Hm, but that ignores the visible flag which would make the
visibility-test.html case fail.

**Comment by spayton** [comment]
I can't say I put a lot of thought into it, saw problem, identified area of problem, looked at how this was handled in Phasers plugin, copied that, problem went away

I just tried my mod and visibility-test seemed to still work.

And furthermore, I created a simple test and it doesn't show my problem, which is very odd, I'll look at it again.

**Comment by spayton** [comment]
ok, here's a broken example (based on visibility-test.html):

```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="//cdn.jsdelivr.net/npm/phaser@3.60.0/dist/phaser.js"></script>
    <script src="../dist/iife/spine-phaser.js"></script>
    <title>Spine Phaser Example</title>
</head>

<body>
    <h1>Visibility Test 2</h1>
</body>
<script>
    const config = {
        type: Phaser.AUTO,
        width: 800,
        height: 600,
        type: Phaser.WEBGL,
        scene: {
            preload: preload,
            create: create,
            pack: {
                files: [
                    { type: "scenePlugin", key: "spine.SpinePlugin", url: "../dist/iife/spine-phaser.js", sceneKey: "spine" }
                ]
            }
        }
    };

    const game = new Phaser.Game(config);

    function preload() {
        this.load.image('coin', 'assets/coin-pma.png');
        this.load.spineBinary("spineboy-data", "assets/spineboy-pro.skel");
        this.load.spineAtlas("spineboy-atlas", "assets/spineboy-pma.atlas");
    }

    function create() {
        const spineboy = this.add.spine(100, 400, 'spineboy-data', "spineboy-atlas");
        spineboy.scale = 0.25;
        spineboy.animationState.setAnimation(0, "idle", true);

        const spineboy2 = this.add.spine(250, 400, 'spineboy-data', "spineboy-atlas");
        spineboy2.scale = 0.25;
        spineboy2.animationState.setAnimation(0, "walk", true);

        window.coin = this.add.image(400,500,'coin').setOrigin(0.5,1).setScale(0.3).setCrop(304,283,286,284);

        const spineboy3 = this.add.spine(500, 400, 'spineboy-data', "spineboy-atlas");
        spineboy3.scale = 0.25;
        spineboy3.animationState.setAnimation(0, "run", true);

        const spineboy4 = this.add.spine(650, 400, 'spineboy-data', "spineboy-atlas");
        spineboy4.scale = 0.25;
        spineboy4.animationState.setAnimation(0, "shoot", true);

        const grp = this.add.container().add([spineboy,spineboy2,coin,spineboy3,spineboy4]);

        this.input.on('pointerdown', () => spineboy2.visible = !spineboy2.visible);
    }
</script>

</html>
```


You will see a row of 4 boys with a coin in the middle, they are all in a container in the order seen:

![image](https://github.com/EsotericSoftware/spine-runtimes/assets/4949575/29dce433-1b20-4d8c-ae76-2f14ef4ceefe)


Clicking anywhere will toggle the visibility of the 2nd boy.

What should happen is that only 2nd boy will disappear/reappear.

Instead, what I observe is missing/corrupt spine rendering:

![image](https://github.com/EsotericSoftware/spine-runtimes/assets/4949575/cd426231-b7c9-4a9f-84d3-24fd9ae9ae2a)

My diagnosis was that when boy2 is being processed and is not visible and the next type has changed (next type is an image), then the call to willRender() returns quickly because of the visible test and doesn't finish off the batching when it should have.

Then when the next game object is rendered, the coin image, because it hasn't reverted back to the phaser renderer, it corrupts the left open batch (boy 1 & boy2). From then on rending of that container is corrupt.

**Comment by badlogic** [comment]
That analysis is absolutely correct. What I meant was, that in the "fixed"
version we still need to integrate the visibility flag check, otherwise it
has no effect. I'll fix this today.

**Comment by badlogic** [comment]
This should be fixed now (for real :D)

**Comment by spayton** [comment]
I'm not sure willRender() needs to check the visible property at all.  When the fix is checked in I'll test it.
