### ISSUE TITLE
[godot] [feature request] Scripts or instructions for building spine-godot with a custom godot branch

### ISSUE THREAD

**Issue by dreed-sd** [EsotericSoftware/spine-runtimes#2463]
We have a fork of godot with a fix integrated that we need. But the scripts and instructions provided for spine-godot assume you want to use the main godot repository. If someone needed 2 such modules that each provided their own separate build scripts, they'd have a problem. Ideally the scripts can be factored so that I can easily prepare the module for compilation into my existing godot fork and using my existing build tools.

I have attempted to build spine-godot alongside our custom fork by looking at what the build scripts provided do, which is mainly copying spine_cpp into spine_godot directory, but I don't know if I'm doing all that is necessary, as I can't get it to work even when just using the built-in scripts as instructed (due to [this issue](https://github.com/EsotericSoftware/spine-runtimes/issues/2462)).

**Comment by badlogic** [comment]
Does your custom branch include your own module as part of the Godot source tree?

I've just pushed a commit to the 4.1 spine-runtimes branch for `spine-godot/build/setup.sh`. You can now specify the Godot repository you want to use as an optional 4th parameter. E.g.

```
./build/setup.sh 4.1.2-stable true false https://github.com/my-github-user/godot.git
```

That will pull in the 4.1.2-stable branch from the repository https://github.com/my-github-user/godot.git

Happy to re-open if this doesn't fit your needs.

**Comment by dreed-sd** [comment]
I think that is a good idea, it should help many users. For us though it's still not ideal. We have a built-out set of scripts for building godot editor and export templates. For example, it compiles a MacOS client and Windows client (cross compiling from the runner's architecture), but the `build-v4.sh` will only compile to mac if you're on a mac, and not also another platform.

I can still just try and work out what the build scripts are doing and integrate those steps into our existing build scripts. It'd be nice if I didn't have to maintain that, such as by calling provided pre-build and post-build scripts in spine-godot. But that's more to maintain for spine-godot, so perhaps not worth the trouble. I'd be more than happy with just documentation on how to include spine-godot in our existing build, such as which directory I need to point custom_modules at, and what I should do to the editor on mac (looks like build-v4.sh copies a macos_tools directory into it?)
