### ISSUE TITLE
[godot] Mismatched registration in Godot bindings causing crash on exit

### ISSUE THREAD

**Issue by Chaosed0** [EsotericSoftware/spine-runtimes#2899]
Our game uses Godot and the `spine-godot` GDExtension. When I exit the game through any means (Godot's quit function or hitting the X on the window), I get a stacktrace like this:

```
================================================================
CrashHandlerException: Program crashed
Engine version: Godot Engine v4.4.1.stable.mono.megadot (941468d5b6a892db5e20920659152d1539735ae1)
Dumping the backtrace. 
[0] RefCounted::reference (C:\godot\megadot\core\object\ref_counted.cpp:66)
[1] RefCounted::reference (C:\godot\megadot\core\object\ref_counted.cpp:66)
[2] ResourceSaver::remove_resource_format_saver (C:\godot\megadot\core\io\resource_saver.cpp:214)
[3] unregister_core_driver_types (C:\godot\megadot\drivers\register_driver_types.cpp:52)
[4] Main::cleanup (C:\godot\megadot\main\main.cpp:4838)
[5] widechar_main (C:\godot\megadot\platform\windows\godot_windows.cpp:102)
[6] _main (C:\godot\megadot\platform\windows\godot_windows.cpp:124)
[7] main (C:\godot\megadot\platform\windows\godot_windows.cpp:136)
[8] __scrt_common_main_seh (D:\a\_work\1\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288)
[9] <couldn't map PC to fn name>
-- END OF BACKTRACE --
================================================================
```

It appears that the Godot engine is attempting to reference the `_extension` field on the `SpineAtlasResourceFormatLoader` after the extension has already been deinitialized.

I dug into why this is occurring. Here is the root cause:

- In Spine's `register_types.cpp`, all GDExtension classes are initiialized at `MODULE_INITIALIZATION_LEVEL_SCENE` (line 91).
- In the same file, resource format loaders and savers are removed at the `MODULE_INITIALIZATION_LEVEL_CORE` step (line 208).

What happens in Godot is this: all the Spine classes get deinitialized through `ClassDB.unregister_extension_class`, which happens in `Main::cleanup` during the call to `GDExtensionManager::deinitialize_extensions(GDExtension::INITIALIZATION_LEVEL_SCENE)`. But references to the resource savers/loaders hang around until `unregister_core_extensions`. Before that occurs, `unregister_core_driver_types` is called, which references the resource savers/loaders indirectly, through the removal of other loaders in its list. This leads to the crash because it tries to reference the extension objects, which have been freed.

It seems like these classes should be registered and de-initialized at the same step. After I apply the below diff, which causes the resource loaders and savers to be initialized at the core level, the crash goes away:

```
diff --git a/spine-godot/spine_godot/register_types.cpp b/spine-godot/spine_godot/register_types.cpp
index f2c11c1fa..6f0f2de91 100644
--- a/spine-godot/spine_godot/register_types.cpp
+++ b/spine-godot/spine_godot/register_types.cpp
@@ -88,6 +88,14 @@ void initialize_spine_godot_module(ModuleInitializationLevel level) {
 		EditorPlugins::add_plugin_class(StringName("SpineEditorPlugin"));
 #endif
 	}
+
+    if (level == MODULE_INITIALIZATION_LEVEL_CORE) {
+        GDREGISTER_CLASS(SpineAtlasResourceFormatLoader);
+        GDREGISTER_CLASS(SpineAtlasResourceFormatSaver);
+        GDREGISTER_CLASS(SpineSkeletonFileResourceFormatLoader);
+        GDREGISTER_CLASS(SpineSkeletonFileResourceFormatSaver);
+    }
+
 	if (level != MODULE_INITIALIZATION_LEVEL_SCENE) return;
 #else
 #if VERSION_MAJOR > 3
@@ -110,10 +118,12 @@ void register_spine_godot_types() {
 #endif
 	spine::Bone::setYDown(true);
 
+#ifndef SPINE_GODOT_EXTENSION
 	GDREGISTER_CLASS(SpineAtlasResourceFormatLoader);
 	GDREGISTER_CLASS(SpineAtlasResourceFormatSaver);
 	GDREGISTER_CLASS(SpineSkeletonFileResourceFormatLoader);
 	GDREGISTER_CLASS(SpineSkeletonFileResourceFormatSaver);
+#endif
 
 	GDREGISTER_CLASS(SpineObjectWrapper);
 	GDREGISTER_CLASS(SpineAtlasResource);
```

However, I'm unsure whether the classes should be registered at the core level, or if the loaders/savers should be removed at the scene level instead.

As a note, I was unable to reproduce this reliably across all machines. I think this has to do with the load order of the Spine extension; there's a chance that `unregister_core_driver_types` will not attempt to reference the Spine resource loaders because they come before the loaders that are being unloaded at that step. Regardless, the mismatch in initialization/removal seems pretty clear.

**Comment by badlogic** [comment]
Thank you for this analysis! I was trying to hunt this down a while ago. Registering/unregistering the loaders/savers at the core level is what we want. Cheers!

**Comment by Chaosed0** [comment]
Glad to hear the analysis was useful! Let me know if I can help by submitting a PR, but I suspect that signing the CLA is more trouble than it's worth for a simple fix.

**Comment by lukeeingram** [comment]
@Chaosed0 I've just submitted a PR that should fix this issue, thank you for your analysis!

**Comment by Chaosed0** [comment]
Hi, any chance I can move this along? It's still an issue for us. I left a small review on the PR but there has not been any response.

**Comment by badlogic** [comment]
I spent some time on this last month and as you've found, Luke's solution was incorrect. I came up with a solution that was supposedly correct, but then started to crash in a different area of the code. Then we needed to add support for Godot 4.5, and I've since not found time to work on this sorry. I'll try to get to it next week.

**Comment by Chaosed0** [comment]
Thanks, appreciate your hard work. Looking forward for the Godot 4.5 release as well :)

**Comment by lukeeingram** [comment]
@Chaosed0 I apologize for the lengthy delay; but I've added your code to this PR:
https://github.com/EsotericSoftware/spine-runtimes/pull/2996

As soon as it passes CI, your fix will be integrated into the 4.2 branch of the spine-godot runtime. Thank you again!
