### ISSUE TITLE
[godot] Double-clicking a .json file in the FileSystem dock causes the editor to crash

### ISSUE THREAD

**Issue by misaki-eymard** [EsotericSoftware/spine-runtimes#2985]
**Description:**
Both editors with the spine-godot GDExtension installed and custom builds of spine-godot crash when double-clicking a file with the “.json” extension in the FileSystem dock. The contents of the .json file are irrelevant to this issue; even if the file is empty, double-clicking any file with the .json extension will always reproduce the crash.

Here is the report obtained after the crash: [error.txt](https://github.com/user-attachments/files/23812489/error.txt)

**Expected behavior:**
In the official Godot Editor (the vanilla editor), double-clicking a .json file in the FileSystem dock switches to the Script screen and displays the file's contents in the code editor. The same behavior is expected in both the spine-godot GDExtension installed editor and in custom spine-godot builds.

**Steps to reproduce:**
1. Open any Godot project using Godot 4.5.1.
2. Import a file with the .json extension. It's fine if the file contains no content.
3. Double-click the .json file imported via the FileSystem dock:  
<img width="274" height="263" alt="Image" src="https://github.com/user-attachments/assets/4c91cb6b-6adb-4345-8539-9b08e35b533c" />. 
4. Then the editor crashes.

**The version of Godot in which this problem was found:**
4.5.1 (Both GDExtension and custom spine-godot builds) / Spine 4.2.43
Tested in 3.6.2 as well, but it appeared that files with the .json extension couldn't be imported at all, so this seems to occur only in 4.x.

**This issue was reported in the following thread on the forum:**
https://esotericsoftware.com/forum/d/29448-godot-crash-when-trying-to-open-a-json-file-on-godot-42-451-stable

**Comment by LucasJackrabbit** [comment]
I have this problem too, also when anything done to animation_mixes array in SpineSkeletonDataResource like adding element (in Inspector), Godot crashes same way, not sure if this is related issue.

**Comment by lukeeingram** [comment]
Fixed in #2996.

**Comment by brwolfless** [comment]
I'm still having this issue in the newest spine-godot engine (Godot 4.6.1).

**Comment by beefchalupa** [comment]
I am also having this exact issue still, with the latest version of Godot and latest spine gd-extension. Double clicking a .json crashes and closes godot.

**Comment by fkyah3** [comment]
## Workaround for Godot 4.5+ Users Still Hitting This

I can confirm this still reproduces in Godot 4.6.1 with the latest Spine GDExtension (2026). The issue is that Spine's EditorImportPlugin still claims the generic  extension, causing crashes when non-Spine JSON files are opened in the editor.

**Workaround**: I've created a GDScript plugin that automatically cleans up incorrect  files created by Spine:

🔗 **Gist**: https://gist.github.com/fkyah3/814b3310559e3af17b0f1aaa307176ad

**How it works**:
- Detects  files created by Spine for non-skeleton JSON
- Identifies real Spine skeletons by checking for keys like , , 
- Removes incorrect imports before they cause the editor crash
- Runs automatically every 10 seconds as a safety net

**Note**: This is a temporary band-aid for teams that need both Spine and JSON config files in the same project. The proper fix would be for Spine to fully migrate to  or for Godot to handle importer conflicts more gracefully.

Hope this helps the community while waiting for an official resolution.
