### ISSUE TITLE
[cocos2d-x] Spine 3.2.01 crash on cocos-2dx 3.10

### ISSUE THREAD

**Issue by linham** [EsotericSoftware/spine-runtimes#611]
i'm seeing a crash in my cocos2dx application when add some SpineAnimation, crash is random, It appears to be loaded too much or too fast. 
The place where cocos2dx crashes is CCRenderer.cpp

void Renderer::fillVerticesAndIndices(const TrianglesCommand* cmd)
{
    memcpy(_verts + _filledVertex, cmd->getVertices(), sizeof(V3F_C4B_T2F) * cmd->getVertexCount());
......

**Comment by linham** [comment]
After an afternoon of hard work, It seems to have found the crash problem. when the SkeletonBatch capacity is not enough, if create more capacity, delete buffer will caush crash.
I comment the   delete [] _buffer, the application not crash again. I hope offical team can slove this problem. Thanks!

**Comment by sbrednikhin** [comment]
Correct. Lost a day to find it.
cocos2dx render holds pointers to vertices but not vertices themselves. 
Resizing _buffer causes loosing of vertices and crash with incorrect stack.

linham - you shouldn't comment delete - it will cause leak. Better way is to extend default buffer size:
replace 
```if (!instance) instance = new SkeletonBatch(8192);```
to 
```if (!instance) instance = new SkeletonBatch(125000);```
It will help for a while.

**Comment by AIGRIND-LLC** [comment]
Faced that issue too.
The workaround from @sbrednikhin works well.
Hope the bug will be completely fixed soon.

**Comment by FrankStain** [comment]
Yep, same here.
Currently i use a lot of skeletons with huge meshes. Found same issue after i updated the runtime.
All was fine on previous version of spine runtime.

**Comment by linham** [comment]
@sbrednikhin yeah, we can do it for a while,  the official team should be updated at the back

**Comment by gitshah** [comment]
Thanks for the fix! I had the same issue.

**Comment by badlogic** [comment]
Could you guys provide me with a sample Spine file that has a mesh huge enough to provoke this issue?

**Comment by sbrednikhin** [comment]
You don't need big mesh, you only need a lots of spine objects. Try about 400-500 skeletons of spineboy-mesh. Or you could just hardcode less number in SkeletonRendered.cpp in 
```
if (!instance) instance = new SkeletonBatch(8192)
```
Bug will be provoked if you will enter inside
```
if (_position + triangles.vertCount > _capacity) {
```
condition inside of SkeletonBatch::addCommand

**Comment by badlogic** [comment]
Great, thanks for the info!

**Comment by badlogic** [comment]
This should be fixed. I set the capacity to 512 in `SkeletonBach::getInstance()` and updated the `BatchingExample` class to draw 500 spine boys. Works as intended.

**Comment by sbrednikhin** [comment]
Sorry for wrong provoking parameters that I gave at first. 
I'v got crash on 1000 spineboys.
Bug is still there, but looks like I was wrong when told you that problem is in buffer resizing.

**Comment by badlogic** [comment]
Ok, I'll give that a try.

**Comment by badlogic** [comment]
Tried again with 4000 spineboys in the `BatchingExample` class, works as intended. I'll re-open if you can provide a reproduction case for me.

**Comment by sbrednikhin** [comment]
Sample from repository:
https://drive.google.com/open?id=0B5m6jiiJkVqgOTQ5YVRtbVJBSmM
Please put cocos2dx engine to spine-cocos2dx\example\cocos2d folder. Don't replace cocos2d_headers.props file. Open win32 solution, compile and run.

**Comment by badlogic** [comment]
This sample only changes the number of spineboys to 1000. I actually set it to 4000 without running into any issues. Still can't reproduce the issue I'm afraid.

**Comment by sbrednikhin** [comment]
Bug was reproduced on 3.11 and 3.12.

**Comment by badlogic** [comment]
Yeah, not on my end. I'll give it a try on Windows as well, though that
shouldn't make a difference.

**Comment by sbrednikhin** [comment]
Updated archive:
https://drive.google.com/open?id=0B5m6jiiJkVqgNm0yTGlydUFqMTQ
cocos2d_headers.props, cocos2dx.props and libcocos2d.vcxproj shouldn't be replaced.

**Comment by linuxshaman** [comment]
Same Issue cocos 3.7.1

**Comment by linuxshaman** [comment]
Quick solution:
1. Add `inline Triangles* getTrianglesRef() { return &_triangles; }` to TrianglesCommand in `CCTriamglesCommand.h.`
2. Replace `memcpy(newBuffer, _buffer, _position);` with `memcpy(newBuffer, _buffer, _position * sizeof(V3F_C4B_T2F));` inside `SkeletonBatch::addCommand`.
3. Add `command->trianglesCommand->getTrianglesRef()->verts = command->triangles->verts;` after `command->triangles->verts = newBuffer + newPosition;` inside `SkeletonBatch::addCommand`.

**Comment by badlogic** [comment]
I'm still having trouble reproducing this issue. Also, it should be possible to fix this without having to modify the cocos2d-x sources. I'm testing on Mac OS X as well as iOS (simulator and ipad) and can't run into any issues. Please provide reproduction steps for me, including OS etc.

**Comment by u0u0** [comment]
The crush reason was described by linham.
For me, I do not understand why SkeletonBatch need a _buffer, because ccoos2dx will
autobetch if self.
I just fix this crush by follow patch for Quick-Cocos2dx-Community [A fork engine from Cocos2d-x],
it avoid crashing and having better performance.

https://github.com/iTyran/Quick-Cocos2dx-Community/commit/cbf8e5163b5fd38dc76c71f1493db34e773cead5

**Comment by badlogic** [comment]
@u0u0 I've applied the fix in the cocos2d-x fork and you are correct: cocos2d-x v3 auto-batching seems to take effect. This should close this issue. Thanks!
